# Base image from Docker Hub:
FROM --platform=$BUILDPLATFORM rocker/rstudio:latest-daily

# Install Seurat R package and (system) dependencies based on 'Dockerfile' (lates - 22/03/2023): 
#https://github.com/satijalab/seurat-docker/blob/master/latest/Dockerfile
# Set global R options
RUN echo "options(repos = 'https://cloud.r-project.org')" > $(R --no-echo --no-save -e "cat(Sys.getenv('R_HOME'))")/etc/Rprofile.site
ENV RETICULATE_MINICONDA_ENABLED=FALSE

# Install Seurat's system dependencies
RUN apt-get update
RUN apt-get install -y \
   build-essential \
   libglpk40 \
   libcairo2-dev libxt-dev \
   libhdf5-dev \
   libcurl4-openssl-dev \
   libssl-dev \
   libpng-dev \
   libboost-all-dev \
   libxml2-dev \
   openjdk-8-jdk \
   python3-dev \
   python3-pip \
   wget \
   git \
   libfftw3-dev \
   libgsl-dev \
   pkg-config \
   llvm-10 \ 
   libgeos-dev \
   cmake

# Install UMAP
RUN LLVM_CONFIG=/usr/lib/llvm-10/bin/llvm-config pip3 install llvmlite
RUN pip3 install numpy
RUN pip3 install umap-learn
# Install FIt-SNE
RUN git clone --branch v1.2.1 https://github.com/KlugerLab/FIt-SNE.git
RUN g++ -std=c++11 -O3 FIt-SNE/src/sptree.cpp FIt-SNE/src/tsne.cpp FIt-SNE/src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm
# Install bioconductor dependencies & suggests
RUN R --no-echo --no-restore --no-save -e "install.packages('BiocManager')"
RUN R --no-echo --no-restore --no-save -e "BiocManager::install(c('multtest', 'S4Vectors', 'SummarizedExperiment', 'SingleCellExperiment', 'MAST', 'DESeq2', 'BiocGenerics', 'GenomicRanges', 'IRanges', 'rtracklayer', 'monocle', 'Biobase', 'limma', 'glmGamPoi'))"
# Install CRAN suggests
RUN R --no-echo --no-restore --no-save -e "install.packages(c('VGAM', 'R.utils', 'metap', 'Rfast2', 'ape', 'enrichR', 'mixtools'))"
# Install spatstat
RUN R --no-echo --no-restore --no-save -e "install.packages(c('spatstat.explore', 'spatstat.geom'))"
# Install hdf5r
RUN R --no-echo --no-restore --no-save -e "install.packages('hdf5r')"
# Install latest Matrix
RUN R --no-echo --no-restore --no-save -e "install.packages('Matrix')"
# Install rgeos
RUN R --no-echo --no-restore --no-save -e "install.packages('rgeos')"
# Install Seurat
RUN R --no-echo --no-restore --no-save -e "install.packages('remotes')"
RUN R --no-echo --no-restore --no-save -e "install.packages('Seurat')"
# Install SeuratDisk
RUN R --no-echo --no-restore --no-save -e "remotes::install_github('mojaveazure/seurat-disk')"

# Packages to cluster single-cell data: 
RUN R --no-echo --no-restore --no-save -e "remotes::install_github('elolab/iloreg', ref='250a4facdaa66977a529fee02b4a8927364b43df')"

# Install CellTypist python package and dependencies: 
RUN pip3 install python-annoy==1.17.0 numpy==1.20.3 scanpy==1.8.2 \
    anndata==0.7.8 hdf5==1.12.1 celltypist==1.0.0 
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('LoomExperiment')"
RUN R --no-echo --no-restore --no-save -e "remotes::install_github('cellgeni/sceasy')"

# Integration data analysis - Scanorama: 
RUN pip3 install scanorama==1.7.3 

# Packages to single-cell trajectory & pseudotime inference:
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('slingshot')"
RUN R --no-echo --no-restore --no-save -e "remotes::install_github('elolab/Totem', ref='fc2d20614a1d82459ca38bb98f22bd212922aec3')"

# Miscellaneous packages/dependencies: 
RUN R --no-echo --no-restore --no-save -e "install.packages('tidyverse')"
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('DelayedMatrixStats')"
RUN R --no-echo --no-restore --no-save -e "install.packages('markdown')"
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('BiocStyle')" 
RUN R --no-echo --no-restore --no-save -e "install.packages('uwot')"

# Packages to import/convert single-cell data into R: 
RUN R --no-echo --no-restore --no-save -e "install.packages('hexbin')"
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('zellkonverter')"
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('DropletUtils')"

# Bioconductor packages for dimensional reduction & processing single-cell data: 
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('scran')" 
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('scater')"

# Descriptions: 
MAINTAINER António Sousa (aggode@utu.fi)
LABEL Description: Toolkit for reproducible single-cell data analyses
LABEL Author(s): António Sousa (aggode@utu.fi)
LABEL Version 1.0.0

